name: GitHub actions workflow
on: [push]
jobs:
   Discover-Github-action-Workflow:
       runs-on : ubuntu-latest
       steps:
          - run : echo "${{github.event.name}} event automatically triggered this job"
          - run : echo "A ${{runner.os}} server has this hosted by Github"
          - run : echo "${{github.repository}} is updated.Updated brach name is $${{github.ref}}"
          - uses : action/checkout@v3
          - run : echo "The runner has cloned the $${{github.repository}} repository"
          - uses : actions/checkout@v3
          - run : echo "The runner has closed the $${{github.repository}} repository"
          - run : ls -l ${{github.workspace}}
          - run : eccho "Push status ${{job.status}}"
